## Numpy Array and basics
learn about numpy easily

In [2]:
import numpy as np

### Creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs numpy array

In [9]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3])
print("Python numpy array multiplication: ", np_array *2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python numpy array multiplication:  [2 4 6]

 List operation time:  0.028280019760131836

 Numpy operation time:  0.0012247562408447266


### Creating array from scratch

In [14]:
zeroes = np.zeros([3, 4])
print("Zeroes Array: \n",zeroes)

ones = np.ones([3, 4])
print("Ones Array: \n", ones)

full = np.full((2, 2), 7)
print("Full Array: \n", full)

random = np.random.random((2, 3))
print("Random Array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array: \n", sequence)

Zeroes Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array: 
 [[0.73199095 0.49175763 0.11123539]
 [0.4051553  0.12037752 0.56624361]]
Sequence Array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [16]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                    [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[[1, 2, 3], [4, 5, 6]],
                    [[5, 6, 7], [8, 10, 11]]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 5  6  7]
   [ 8 10 11]]]]


### Array Properties

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimnsions: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Shape:  (3, 3)
Dimnsions:  2
Size:  9
Data Type:  int64


### Array Rehaping

In [25]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped Array: ", reshaped)

# Changes the original array
flattened = reshaped.flatten()
print("Flattened Array: ", flattened)

print(reshaped)

# Only returns the view do not change the original array
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("Transpose: ", transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
