## Numpy array operations

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("Basic slicing: ", arr[1:5])
print("Step slicing: ", arr[1:5:2])
print("Negative indexing: ", arr[-3])

Basic slicing:  [2 3 4 5]
Step slicing:  [2 4]
Negative indexing:  5


### 2D Array

In [4]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print("Specific Element: ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific Element:  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [5]:
unsorted = np.array([3, 1, 3, 5, 8, 7, 0, 9])
print("sorted array: ", np.sort(unsorted))

array_2d_unsorted = np.array([[3, 1], [2, 4], [8, 3]])
print("Sorted 2D array by column: ", np.sort(array_2d_unsorted, axis=1)) # axis is used for sorting array by column(axis=0) or row(axis=1) wise

sorted array:  [0 1 3 3 5 7 8 9]
Sorted 2D array by column:  [[1 3]
 [2 4]
 [3 8]]


## Filter

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Numpy library allows us to use expresions in the same [] place of indexing
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


### Filter with mask

In [7]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [8]:
indices = [0, 2, 4]
print(numbers[indices])

[1 3 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

where_result = np.where(arr > 4) # With only condition it returns indexes of the values where the condition is true
print(where_result)


(array([4, 5]),)


In [13]:
# In this example if the condition is true then the value that would be returned will be true and if false then False will be returned
condition_array = np.where(arr > 4, True, False) # With the condition and the if_true and if_false it returns the value of these
print(condition_array)

[False False False False  True  True]


### Adding and removing data

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Compatibility Arrays

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])

print("Compatibility Shape Check (a & b): ", a.shape == b.shape)
print("Compatibility Shape Check (b & c): ", b.shape == c.shape)

Compatibility Shape Check (a & b):  True
Compatibility Shape Check (b & c):  False


In [ ]:
# vstack (Vertical stack) and hstack (Horzontal Stack)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

with_np_vstack = np.vstack((arr1, arr2)) # Adds new row
print("VSTACK:\n", with_np_vstack)

with_np_hstack = np.hstack((arr1, arr2)) # Adds new Column
print("HSTACK:\n", with_np_hstack)

VSTACK:
 [[1 2 3]
 [4 5 6]]
HSTACK:
 [1 2 3 4 5 6]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Array before deletion: ", arr)

deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array before deletion:  [1 2 3 4 5 6]
Array after deletion:  [1 2 4 5 6]
